# Generated by Django 4.0.3 on 2022-04-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_task_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
